//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wsdot.Geodatabase.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wsdot.Geodatabase.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- DECLARE @name as nvarchar(226) = &apos;LRS.DBO.GPSLRSStatwide&apos;
        ///SELECT [Documentation]
        ///FROM [LRS].[dbo].[GDB_ITEMS]
        ///WHERE [Name] LIKE @name.
        /// </summary>
        internal static string GetMetadata {
            get {
                return ResourceManager.GetString("GetMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT [name]
        ///  FROM [master].[sys].[databases]
        ///  WHERE [owner_sid] &lt;&gt; 0x01
        ///  ORDER BY [name].
        /// </summary>
        internal static string ListDatabases {
            get {
                return ResourceManager.GetString("ListDatabases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT        i.Name, i.PhysicalName, i.Path, t.Name AS Type, t.UUID AS TypeUuid, t.ParentTypeID
        ///FROM            dbo.GDB_ITEMS AS i INNER JOIN
        ///                         dbo.GDB_ITEMTYPES AS t ON i.Type = t.UUID
        ///WHERE        (t.Name LIKE &apos;Feature%&apos;)
        ///ORDER BY i.Path.
        /// </summary>
        internal static string ListFeatureClassesAndFeatureDatasets {
            get {
                return ResourceManager.GetString("ListFeatureClassesAndFeatureDatasets", resourceCulture);
            }
        }
    }
}
